
platform :ios, '8.0'
use_frameworks!

target 'Cardyo' do

pod 'ZLSwipeableViewSwift'
pod 'performSelector-swift'
pod 'UIColor+FlatColors'
pod 'Cartography'
pod 'ReactiveUI'
pod 'AFNetworking', '~> 2.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Alamofire', '~> 3.0'
pod 'KeyboardWrapper'
pod 'RealmSwift'
pod 'APIModel', '~> 0.10.0'

end

target 'CardyoTests' do

end

target 'CardyoUITests' do

end

